In [2]:
from math import factorial
import math
import numpy as np

In [3]:
## Даны значения зарплат из выборки выпускников:
## 100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150.
## Посчитать (желательно без использования статистических методов наподобие std, var, mean) 
## среднее арифметическое, среднее квадратичное отклонение, смещенную и несмещенную оценки дисперсий для данной выборки.

In [4]:
a = np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])
a

array([100,  80,  75,  77,  89,  33,  45,  25,  65,  17,  30,  24,  57,
        55,  70,  75,  65,  84,  90, 150])

In [37]:
np.std([a])

30.823854398825596

In [38]:
np.var(a)

950.11

In [5]:
np.sum(a)

1306

In [6]:
np.shape(a)


(20,)

In [7]:
## Среднее арифметическое
B = np.sum(a)/np.shape(a)
B

array([65.3])

In [17]:
C =np.sum(pow((a-B),2))
C

19002.2

In [40]:
## Смещенная дисперсия
S2 = C/np.shape(a)
S2

array([950.11])

In [42]:
## Среднее квардатичное отклонение
S = pow(S2 , 0.5)
S

array([30.8238544])

In [43]:
## Несмещенная дисперсия
S3 = C/19
S3

1000.1157894736842

In [44]:
## Несмещенной среднее квадратичное отклонение
S = pow(S3 , 0.5)
S

31.624607341019814

2. В первом ящике находится 8 мячей, из которых 5 - белые. 
Во втором ящике - 12 мячей, из которых 5 белых. Из первого ящика вытаскивают случайным образом два мяча,
из второго - 4.
Какова вероятность того, что 3 мяча белые?

In [46]:
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

In [49]:
## 2 белых из первой корзины, 1 белый +3 черных из второй корзины
P1 = combinations(5, 2)/combinations(8, 2) * combinations(5,1)*combinations(7,3)/combinations(12, 4)
P1

0.12626262626262627

In [50]:
## 1 белый+ 1 черный из первой корзины, 2 белый +2 черных из второй корзины
P2 = combinations(5, 1)*combinations(3, 1) /combinations(8, 2) * combinations(5,2)*combinations(7,2)/combinations(12, 4)
P2

0.22727272727272724

In [56]:
## 2 черных из первой корзины + 0 белых, 3 белый +1 черный из второй корзины
P3 = (combinations(5, 0)*combinations(3, 2) /combinations(8, 2)) * (combinations(5,3)*combinations(7,1)/combinations(12, 4))
P3

0.01515151515151515

Вероятность. что будут 3 белых шара:

In [57]:
P = P1+P2+P3
P

0.3686868686868686

3.На соревновании по биатлону один из трех спортсменов стреляет и попадает в мишень. 
Вероятность попадания для первого спортсмена равна 0.9, для второго — 0.8, для третьего — 0.6.
Найти вероятность того, что выстрел произведен: a). первым спортсменом
    б). вторым спортсменом в). третьим спортсменом.

Вероятность выстрела для каждого спортсмена составляет 1/3
Вероятность попадания выстрела для первого спортсмена составляет 0,9
Вероятность что выстрел, произведенный одним из 3 спорстменов с результатом: попадание был произведен первым спорстменом равна


In [58]:
P1= 0.9/3
P1

0.3

Вероятность попадания выстрела для второго спортсмена составляет 0,8
Вероятность что выстрел, произведенный одним из 3 спорстменов с результатом: попадание был произведен вторым спорстменом равна


In [59]:
P2= 0.8/3
P2

0.26666666666666666

Вероятность попадания выстрела для третьего спортсмена составляет 0,6
Вероятность что выстрел, произведенный одним из 3 спорстменов с результатом: попадание был произведен третьим спорстменом равна

In [60]:
P3= 0.6/3
P3

0.19999999999999998

4. В университет на факультеты A и B поступило равное количество студентов, а на факультет C студентов поступило столько же, сколько на A и B вместе. Вероятность того, что студент факультета A сдаст первую сессию, равна 0.8. Для студента факультета B эта вероятность равна 0.7, а для студента факультета C - 0.9. Студент сдал первую сессию. Какова вероятность, что он учится: a). на факультете A б). на факультете B в). на факультете C?

In [ ]:
Вероятность, что экзамен сдавал студент факультета А = 1/4, В = 1/4, С = 1/2.
Вероятность, что первую сессию сдал студент, который учится на: 

In [62]:
##  факультете А:   
PA = 0.8 *1/4
PA

0.2

In [63]:
## факультете B
PB = 0.7 *1/4
PB

0.175

In [64]:
## факультете С
PС = 0.9 *1/2
PС

0.45

5. Устройство состоит из трех деталей. Для первой детали вероятность выйти из строя в первый месяц равна 0.1, для второй - 0.2, для третьей - 0.25. Какова вероятность того, что в первый месяц выйдут из строя: а). все детали б). только две детали в). хотя бы одна деталь г). от одной до двух деталей?

In [65]:
## Вероятность. что выйдут все три детали в первый месяц:
P = 0.1*0.2*0.25
P

0.005000000000000001

In [66]:
## Вероятность, что выйдут только 2 детали в первый месяц:
## выйдут из строz первая и вторая деталь, а третья будет работать
P1 = 0.1*0.2*(1-0.25)
P1

0.015000000000000003

In [67]:
## выйдут из строя первая и третья деталь, а вторая будет работать
P2 = 0.1*(1-0.2)*(0.25)
P2

0.020000000000000004

In [68]:
## выйдут из строя вторая и третья деталь, а первая будет работать
P3 = (1-0.1)*(0.2)*(0.25)
P3

0.045000000000000005

In [71]:
## Вероятность, что выйдут только 2 детали в первый месяц:
P4 =P1+P2+P3
P4

0.08000000000000002

In [72]:
## Вероятность, что выйдeт хотя бы одна деталь. Надо найти вероятность, когда из строя не выйдет ни одна деталь:
P5 = (1-0.1)*(1-0.2)*(1-0.25)
P5

0.54

In [73]:
## Вероятность, что выйдет хотя бы одна деталь:
P6 = 1-0.54
P6

0.45999999999999996

In [78]:
## Вероятность, что выйдут от 1 до 2 детали в первый месяц:
## Вероятность, что выйдет из строя одна деталь:
P7 = (0.1)*(0.2)*(0.25)
P7

0.005000000000000001

In [76]:
## Вероятность, что выйдет из строя только две детали:
P8 = P4
P8

0.54

In [79]:
## Вероятность, что выйдет из строя от одной до двух деталей:
P9 =P7+P8
P9

0.545